weights: weights/yolov5s.pt
cfg: ./models/yolov5s.yaml
data: data/healthcare.yaml
hyp: data/hyp.scratch.yaml
epochs: 150
batch_size: 5
img_size:
- 1600
- 1600
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: true
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
workers: 8
project: runs/train
name: yolov5s_uncropped_results_filtered
exist_ok: false
total_batch_size: 5
world_size: 1
global_rank: -1
save_dir: runs/train/yolov5s_uncropped_results_filtered
